### PR TITLE
Github support --- Part 1

### PR DESCRIPTION
**Pull request by americast**
@athityakumar Since I was unable to find a way to create JSON files using octokit, I have used .txt files.

Gramercy,
Sayan Sinha.
(kwoc_student)

### CODE REVIEW

**Comment by athityakumar** [comment]
@americast  - Infact, it's not necessary to use octokit gem. You can directly use curl statements from Ruby with backticked statements, like `curl -u ....` to store the data into JSON files. Then, you can use inbuilt gem "JSON" of ruby to check for output.

Also, using curl statements to store into JSON files is much better, because support can later be extended to python and other languages too, as JSON parsing is quite basic and easily done.

**Comment by americast** [comment]
@athityakumar I have implemented new followers list using JSON. The authentication part still uses octokit. Is it okay or should I add more features....?

**Comment by americast** [comment]
@athityakumar Added new issues using curl/JSON

**Comment by americast** [comment]
@athityakumar Added new stargazers and new forkers

**Comment by americast** [comment]
@athityakumar Added PRs. Also added a percentage complete stamp...
In case of PRs, it will list all the PRs which have received updates (like commits, comments etc.) and the ones which are new will have a labelling "*NEW"...

**Comment by americast** [comment]
@athityakumar Added reverse support (i.e. unforkers, closed PRs, etc.)

**Comment by americast** [comment]
@athityakumar Removed octokit.

All features have been added. Pl consider reviewing and merging the PR.

**Comment by athityakumar** [comment]
@americast - Great work till now. Cheers! 

I keep getting this error.The github_login function is  executed before the mkdir_p statements, and hence the error. Fix this. 

image

Some suggestions -

(1) Keep all "intermediate" data files in the same directory (instead of data/github/) as the main.rb and helper.rb files, and delete them after concatenating them into one big `data.json` json file. For example, 

For followers : Only username is required.
For PRs : PR title , number, link, submitter and status (open / closed/ merged) fields are required.
For issues : Same fields as PRs are required.
For stargazers & forkers : Repo name, and usernames of stargazers / forkers are required fields. 

Also, most results are paginated. Take care to cover all results with curl  like - `curl --user "{user}:{key}" https://api.github.com/users/{user}/{page}?page\={page_number}\&per_page\=100 -o filename.json`.

(2) Silence the curl outputs with option `-s`

(3) Use inbuilt ruby libraries like `Dir` rather than `FileUtils`. Also, for executing shell commands from ruby script, use backticks like ``echo Hello`` rather than `system()` calls.

(4) Use puts with variables itself like `puts "Variable is #{var}"`, rather than `puts "Variable is"; print var;` 

(5) Edit the `.gitignore` to ignore the `secrets/` directory.

(6) If you have time, do split the code into functions rather than just a single big function. Makes debugging and reading the codes much easier.

**Comment by athityakumar** [comment]
@americast : Great! All functionalities are working. Only pagination is left - ie, by default, only the first 40 repos / followers / stargazers / forkers / issues / PRs will be given as curl reponse. So, you have to make the code travel through all the pages . Once that has been done, just small changes like changing the messages' semantic, and adding functionality of mailing the same data to the user's gmail account is remaining. :smile:

**Comment by americast** [comment]
@athityakumar How can I mail the data? What I can do is save the data generated in a file and open it with mailing apps like thunderbird or gmail-notifier... Is that what you mean...?
And for the semantic, you may tell me how you want the message to be displayed. But I feel it would be better if you would customize that yourself....

**Comment by athityakumar** [comment]
@americast - You can install a command line utility called `sendmail`.

**Comment by americast** [comment]
@athityakumar I have added the feature you requested.

**Comment by americast** [comment]
@athityakumar Mail will be sent to the address registered on GitHub...

Pl comment...

**Comment by athityakumar** [comment]
@americast : I have tested twice, but I haven't got the mail yet, it's probably being treated as Exception somewhere. Also, can you create a list `messages` and `push` each message being displayed into it, and write it into a json file with fields that I've mentioned above? That is, use only fields mentioned below -

For followers : Only username is required.
For PRs : PR title , number, link, submitter and status (open / closed/ merged) fields are required.
For issues : Same fields as PRs are required.
For stargazers & forkers : Repo name, and usernames of stargazers / forkers are required fields.

**Comment by athityakumar** [comment]
@americast : ^ That way, we'll have only one JSON file with all data rather than separate file for each repo, that looks like this :
<pre>
[
    {
        "notification_type" : "follower",
        "data" : ["username1","username2"]
    },
    {
        "notification_type" : "issue",
        "data" : [
            {
                "submitted_by" : "username", 
                "repo_name" : "repo_owner_username/repo_name",
                "title" : "issue_number + issue_title",
                "link" : "issue_url",
                "status" : "open"
            }
        ]
    },
    {
        "notification_type" : "pr",
        "data" : [
            {
                "submitted_by" : "username", 
                "repo_name" : "repo_owner_username/repo_name",
                "title" : "pr_number + pr_title",
                "link" : "pr_url",
                "status" : "merged"
            }
        ]
    },
    {
        "notification_type" : "fork",
        "data" : [
            {
                "username" : "username",
                "repo" : "repo_owner_username/repo_name"
            }
        ]
    },
    {
        "notification_type" : "star",
        "data" : [
            {
                "username" : "username",
                "repo" : "repo_owner_username/repo_name"
            }
        ]
    }    
]
</pre>

**Comment by americast** [comment]
@athityakumar What's the harm in having separate file for each repo? I think that's better as anyone will easily be able to extract the required data in the future.

**Comment by athityakumar** [comment]
@americast - I think that the `mail.txt` isn't created properly and hence `sendmail` is also not sending the mail. So, we'll need a template file for the `mail.txt` and also for that template, it'd be easier if all data is stored is stored in just one file - rather than reading from multiple files.

**Comment by americast** [comment]
@athityakumar mail.txt is being created just to check if sendmail is installed (and running). In case it's not, reading from it return an EOF exception and the option to send a mail is not displayed...Is the command to send a mail using sendmail correct (lines 406-408)?

**Comment by athityakumar** [comment]
@americast : This is the correct format - `sendmail -f {from_mail_id} {to_mail_id} < mail.txt`, and mail.txt should be something like this -

<pre>
To: {to_mail_id}
From: {from_mail_id}
Subject: Daily Update of Github Notifications
Content-Type: text/html

<p> Dear <a href="{github_profile_url}">@{user_name}</a>, </p>
<p>
I have some Github Notifications you might be interested to have a look at. These notifications are from {last_updated_date} - {today_date}. </p>
<p>
<ul>
<li> {X} starred your repository : {username}/{repository} </li>
<li> {Y} followed you </li>
<li> {Z} unfollowed you </li>
<li> {A} forked your repository : {username}/{repository} </li>
<li> Open issue : {issue}{issue_link} </li>
<li> Open PR : {PR}{PR_link} </li>
</ul>
</p>
<p>Have an awesome day! </p>
<p> Yours sincerely, </p>
<p> GitHub Notifier <a href="http://github.com/athityakumar/github-notifier">(View source code on GitHub)</a>. </p>
</pre>

**Comment by americast** [comment]
@athityakumar How may I know the from_mail_id?

**Comment by athityakumar** [comment]
@americast - While executing locally, both `from` and `to` mail IDs will be set as same. If we're going to deploy to some server like Heroku, then we can create some bot mail ID, and keep it as the `from` mail ID.

**Comment by americast** [comment]
@athityakumar I have updated the sendmail part. Now mail.txt will contain the message. Have a look and comment...

**Comment by americast** [comment]
@athityakumar Fixed sendmail formatting....sendmail is working, I received a mail :-)

Pl comment...

**Comment by athityakumar** [comment]
Thanks for the quick commits addressing the changes suggested, @americast. :smile: :+1:  

This PR is becoming large, so I'll merge it for now. You can make other contributions as suggested in issue #2 and start on a new PR after re-forking my repo.

**Comment by athityakumar** [comment]
@americast - Also, by issues, I meant to track issues in all repos of the user, and not the issues assigned to the user.

**Pull request merged**
